name: Ultralesson Web Automation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Chrome browser
        uses: browser-actions/setup-chrome@latest
        with:
          version: '94.0.4606.41'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v1
        with:
          arguments: build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Setup Chrome browser
        uses: browser-actions/setup-chrome@latest
        with:
          version: '94.0.4606.41'
      - name: Run Selenium Tests with Gradle
        uses: gradle/gradle-build-action@v1
        with:
          arguments: runWebTests -Dbrowser.headless=true
      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-reports
          path: build/reports/tests
